# Generated by Django 5.2.1 on 2025-05-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fluent_app", "0002_conversationtemplate_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="log",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
